require 'origen'
require_relative '../config/application.rb'
require 'origen_jtag'
require 'origen_swd'

module OrigenARMDebug
  require 'origen_arm_debug/helpers'
  require 'origen_arm_debug/dap'
  require 'origen_arm_debug/dap_controller'
  require 'origen_arm_debug/dp_controller'
  require 'origen_arm_debug/jtag_dp'
  require 'origen_arm_debug/jtag_dp_controller'
  require 'origen_arm_debug/sw_dp'
  require 'origen_arm_debug/sw_dp_controller'
  require 'origen_arm_debug/ap'
  require 'origen_arm_debug/ap_controller'
  require 'origen_arm_debug/mem_ap'
  require 'origen_arm_debug/mem_ap_controller'
  require 'origen_arm_debug/jtag_ap'
end
